parameters:
  - name: terraformOperation
    displayName: Terraform operation
    type: string
    default: ''

stages:
- ${{ if eq(parameters.terraformOperation, 'init') }}:
  - stage: Terraform_init
    variables:
    - group: powershelluniversal-webapp
    #- template: variables.yml
    jobs:
    - job: Terraform_init
      pool:
        vmImage: 'vs2017-win2016'

      steps:

      - task: PowerShell@2
        inputs:
          targetType: inline
          script: |
            $releasesUrl = 'https://api.github.com/repos/hashicorp/terraform/releases'
            $releases = Invoke-RestMethod -Method Get -UseBasicParsing -Uri $releasesUrl -Verbose
            $downloadVersion = $releases.Where({!$_.prerelease})[0].name.trim('v')
            $terraformFile = "terraform_${downloadVersion}_windows_amd64.zip"
            $terraformURL = "https://releases.hashicorp.com/terraform/${downloadVersion}/${terraformFile}"
            $output = "$(Agent.TempDirectory)\terraform.zip"
            $wc = New-Object System.Net.WebClient
            $wc.DownloadFile($terraformURL, $output)
            Unblock-File -Confirm:$false -Path "$(Agent.TempDirectory)\terraform.zip"
            $newDir = New-Item -ItemType Directory -Path "$(Agent.TempDirectory)\terraform"
            Expand-Archive -Path "$(Agent.TempDirectory)\terraform.zip" -DestinationPath $newDir.FullName -Force
            Copy-Item "$(Agent.TempDirectory)\terraform\terraform.exe" -Destination "$(System.DefaultWorkingDirectory)\IaC\terraform.exe"

      - task: PowerShell@2
        inputs:
          targetType: inline
          script: |
            Get-ChildItem -Path "$(System.DefaultWorkingDirectory)\IaC" -Recurse -Verbose
            Set-Location $(Build.SourcesDirectory)\IaC
            .\terraform.exe init -backend-config="$(terraform-cloud-secret)"
