parameters:
  - name: terraformOperation
    displayName: Terraform operation
    type: string
    default: ''

stages:
- ${{ if eq(parameters.terraformOperation, 'init') }}:
  - stage: Terraform_init  # name of the stage (A-Z, a-z, 0-9, and underscore)
    displayName: 'Terrafrom init'  # friendly name to display in the UI
    dependsOn: []
    jobs:
    - deployment: init   # name of the deployment job, A-Z, a-z, 0-9, and underscore. The word "deploy" is a keyword and is unsupported as the deployment name.
      displayName: 'Terraform init'  # friendly name to display in the UI
      pool:                # see pool schema
        vmImage: 'vs2017-win2016' #'Ubuntu-16.04' #"vs2017-win2016" #Ubuntu-latest
        demands: []
      workspace:
        clean: all # what to clean up before the job runs
      continueOnError: true                # 'true' if future jobs should run even if this job fails; defaults to 'false'
      timeoutInMinutes: 3       # how long to run the job before automatically cancelling
      cancelTimeoutInMinutes: 2  # how much time to give 'run always even if cancelled tasks' before killing them
      #variables: # several syntaxes, see specific section
      environment: Azure # target environment name and optionally a resource name to record the deployment history; format: <environment-name>.<resource-name>
      strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - task: PowerShell@2
              inputs:
                targetType: inline
                script: |
                  $releasesUrl = 'https://api.github.com/repos/hashicorp/terraform/releases'
                  $releases = Invoke-RestMethod -Method Get -UseBasicParsing -Uri $releasesUrl
                  $terraformURL = $releases[0].html_url
                  $download = Invoke-WebRequest -UseBasicParsing -Uri $terraformURL -DisableKeepAlive -OutFile "$(Agent.TempDirectory)\terraform.zip" -ErrorAction SilentlyContinue -PassThru
                  Unblock-File -Confirm:$false -Path "$(Agent.TempDirectory)\terraform.zip"
#
#            - task: PowerShell@2
#              inputs:
#                targetType: inline
#                script: |
#                  Get-ChildItem $(Pipeline.Workspace) -Recurse -Verbose
#                  #Set-Location $(Pipeline.Workspace)\IaC
#                  terraform init
